# Generated by Django 5.2.7 on 2025-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_user_age_user_dob_user_gender_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('apartment', 'Full Apartment')], default='private', max_length=10),
        ),
    ]
