# Generated by Django 5.2.7 on 2025-11-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_user_address_user_city_user_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('pg', 'PG / Paying Guest'), ('hostel', 'Hostel')], max_length=10, null=True),
        ),
    ]
