# Generated by Django 5.2.7 on 2025-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_post_average_rating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='post',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
