# Generated by Django 5.2.7 on 2025-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_rename_location_post_street_address_post_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
