# Generated by Django 5.2.7 on 2025-11-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_tenancy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies_history', to='homepage.post'),
        ),
    ]
