# Generated by Django 5.2.7 on 2025-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_remove_post_latitude_remove_post_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='homepage.user'),
        ),
    ]
