"""
Django settings for SomeNew project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Vercel build aur runtime dono me VERCEL=1 milta hai (system env var).
ON_VERCEL = bool(os.getenv("VERCEL"))


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

# SECRET_KEY: local `.env` se ya Vercel ke Environment Variables se aata hai.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if ON_VERCEL:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable set nahi hai. Vercel -> Project -> "
            "Settings -> Environment Variables me SECRET_KEY add karo."
        )
    # Local development ke liye temporary key (server restart pe sessions reset honge).
    SECRET_KEY = "django-insecure-local-dev-only-" + secrets.token_urlsafe(40)

# DEBUG: Vercel pe default False, local pe default True.
DEBUG = os.getenv("DEBUG", "False" if ON_VERCEL else "True").strip().lower() == "true"

# ALLOWED_HOSTS: localhost + Vercel deployments + custom domains.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", ".vercel.app"]
ALLOWED_HOSTS += [h.strip() for h in os.getenv("EXTRA_ALLOWED_HOSTS", "").split(",") if h.strip()]
for _host_env_var in ("VERCEL_URL", "VERCEL_BRANCH_URL", "VERCEL_PROJECT_PRODUCTION_URL"):
    _host = os.getenv(_host_env_var)
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

# CSRF: HTTPS origins (Vercel TLS terminate karta hai).
CSRF_TRUSTED_ORIGINS = ["https://*.vercel.app"]
CSRF_TRUSTED_ORIGINS += [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in ("localhost", "127.0.0.1", "[::1]") and not host.startswith(".")
]
CSRF_TRUSTED_ORIGINS += [o.strip() for o in os.getenv("EXTRA_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# Vercel proxy ke peeche request.is_secure() sahi kaam kare.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    # 'daphne' ASGI dev-server (`runserver`) deta hai, isliye local pe
    # WebSocket (chat + notifications) test kiye ja sakte hain.
    # Vercel pe ye khud ASGI app chalata hai, wahan iski zarurat nahi.
    'daphne',
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'homepage.apps.HomepageConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SomeNew.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SomeNew.wsgi.application'
ASGI_APPLICATION = 'SomeNew.asgi.application'

# ---------------------------------------------------------------------------
# Channel layers (WebSockets: chat + live notifications)
# ---------------------------------------------------------------------------
# InMemoryChannelLayer sirf ek hi process ke andar kaam karta hai. Vercel pe
# multiple function instances hote hain, isliye production me REDIS_URL set karo
# (Upstash Redis from Vercel Marketplace). Uske liye requirements.txt me se
# `channels-redis` install karna hoga.
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        # Serverless: har invocation pe fresh connection (stale connection errors se bachne ke liye).
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "0")),
        "OPTIONS": {
            # Cloud Postgres (Neon/Supabase) SSL maangta hai; local Postgres "prefer" se chal jata hai.
            "sslmode": os.getenv("DB_SSLMODE", "require" if ON_VERCEL else "prefer"),
            "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "10")),
        },
        # Neon/Supabase ke pooled endpoint (PgBouncer, transaction mode) ke saath
        # server-side cursors band rakhne padte hain.
        "DISABLE_SERVER_SIDE_CURSORS": os.getenv(
            "DB_DISABLE_SERVER_SIDE_CURSORS", "True" if ON_VERCEL else "False"
        ).strip().lower() == "true",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# Vercel ke build ke waqt STATIC_ROOT `public/<STATIC_URL>/` pe override hota hai
# aur wahan se files Vercel CDN serve karta hai. Isliye STATIC_ROOT set hona
# zaroori hai, warna Vercel collectstatic skip kar deta hai.

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Media files (user-uploaded content)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Vercel ka filesystem read-only hai, isliye naye uploads (profile photo, post
# images, maintenance photos) disk pe save nahi ho sakte. Neeche diye gaye env
# vars set karte hi S3-compatible cloud storage on ho jata hai
# (AWS S3 / Supabase Storage / Cloudflare R2). Iske liye requirements.txt me se
# `django-storages[s3]` install karna hoga.
USING_CLOUD_MEDIA = bool(os.getenv("AWS_STORAGE_BUCKET_NAME"))
if USING_CLOUD_MEDIA:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
                "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
                "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
                "endpoint_url": os.getenv("AWS_S3_ENDPOINT_URL") or None,
                "region_name": os.getenv("AWS_S3_REGION_NAME") or None,
                "custom_domain": os.getenv("AWS_S3_CUSTOM_DOMAIN") or None,
                "file_overwrite": False,
                "querystring_auth": False,
            },
        },
        # Static files Vercel CDN se serve hote hain -> staticfiles ke liye
        # default (FileSystem) backend hi rakha gaya hai.
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# NOTE: Vercel Functions ka request/response body limit 4.5 MB hai. Isse badi
# image upload karne pe Vercel 413 (FUNCTION_PAYLOAD_TOO_LARGE) return karega.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

